version: "3.8"

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    volumes:
      - 3x-ui-db:/etc/x-ui/
      - 3x-ui-cert:/root/cert/
    networks:
      - bridge
      - server
    ports:
      - '30000-30050'
    restart: unless-stopped

  vpn-pihole:
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Moscow'
      DNSSEC: 'true'
    volumes:
      - vpn-pihole:/etc/pihole
      - vpn-pihole-dnsmasq:/etc/dnsmasq.d
    networks:
      - bridge
      - server
    restart: unless-stopped

  public-pihole:
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Moscow'
      DNSSEC: 'true'
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    volumes:
      - public-pihole:/etc/pihole
      - public-pihole-dnsmasq:/etc/dnsmasq.d
    networks:
      - bridge
      - server
    restart: unless-stopped

volumes:
  3x-ui-db:
  3x-ui-cert:
  vpn-pihole:
  vpn-pihole-dnsmasq:
  public-pihole:
  public-pihole-dnsmasq:

networks:
  bridge:
  server:
    external: true
